description: UBC's CTF team
exclude: [.gitignore, Gemfile, Gemfile.lock, README.md, vendor]
permalink: /:categories/:year/:month/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


collections:
  authors:
    output: true